<a href="https://colab.research.google.com/github/Clinton1029/bankruptcy_pred/blob/main/Bankruptcy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comparative Analysis of Decision Tree and Random Forest Classification Models for Company Bankruptcy Prediction

### Final Year Project

**Student:** kipchirchir Nimrode

**Institution:** Dedan Kimathi University of Technology  
**Department:** Mathematics and Physical Sciences  
**Programme:** BSc in Mathematics and Modelling Processes

## 1. Introduction

Company bankruptcy prediction is an important application of machine learning in financial risk management. Financial institutions, investors, and company managers need reliable methods for identifying companies that are at risk of bankruptcy.

This project develops and compares two machine learning classification models, Decision Tree and Random Forest, for predicting company bankruptcy. The models will be trained using historical company financial indicators and evaluated using appropriate classification performance metrics.

## Problem Statement

Company bankruptcy can result in financial losses, business failure, and difficulties for investors and other stakeholders. Therefore, reliable machine learning models are needed to predict company bankruptcy using financial indicators and support better financial risk assessment.

## 2. Project Workflow

The project will follow the following steps:

1. Import Required Libraries
2. Load the Dataset
3. Exploratory Data Analysis (EDA)
4. Data Preprocessing and Preparation
5. Feature Selection and Feature Importance
6. Split the Dataset into Training and Testing Sets
7. Choose the Machine Learning Models
8. Train the Machine Learning Models
9. Make Predictions
10. Evaluate Model Performance
11. Compare Decision Tree and Random Forest
12. Predict Bankruptcy Status for New Company Financial Data

###1 Import Required Libraries

The first step in developing the company bankruptcy prediction models is to import the required Python libraries. These libraries will support data manipulation, exploratory data analysis, data visualization, preprocessing, feature selection, model development, and performance evaluation.

The study will use Pandas and NumPy for data manipulation, Matplotlib and Seaborn for visualization, and Scikit-learn for preprocessing, training, and evaluating the Decision Tree and Random Forest classification models.

In [10]:
# Import os for interacting with the operating system and managing file paths
import os

# Import Pandas for loading, organizing, and manipulating tabular financial data
import pandas as pd

# Import NumPy for numerical computations and array operations
import numpy as np

# Import Matplotlib for creating charts and visualizing data
import matplotlib.pyplot as plt

# Import Seaborn for creating statistical visualizations
import seaborn as sns

# Import train_test_split to divide the dataset into training and testing sets
from sklearn.model_selection import train_test_split

# Import DecisionTreeClassifier to build the Decision Tree classification model
from sklearn.tree import DecisionTreeClassifier

# Import RandomForestClassifier to build the Random Forest classification model
from sklearn.ensemble import RandomForestClassifier

# Import accuracy_score to calculate the proportion of correct predictions
from sklearn.metrics import accuracy_score

# Import precision_score to measure the proportion of predicted bankrupt cases that are correct
from sklearn.metrics import precision_score

# Import recall_score to measure the proportion of actual bankrupt cases correctly identified
from sklearn.metrics import recall_score

# Import f1_score to calculate the harmonic mean of precision and recall
from sklearn.metrics import f1_score

# Import confusion_matrix to summarize correct and incorrect classifications
from sklearn.metrics import confusion_matrix

# Import roc_auc_score to evaluate how well the model distinguishes between the two classes
from sklearn.metrics import roc_auc_score

# Display a message confirming that the libraries have been imported
print("All required libraries have been imported successfully.")

All required libraries have been imported successfully.

### 2. Load the Dataset

The next step is to load the company bankruptcy dataset into the Google Colab environment. The dataset contains financial indicators that will be used as predictor variables and a target variable, `Bankrupt`, that represents the bankruptcy status of each company.

The dataset will be loaded using the Pandas library. After loading, the first few records, dataset dimensions, column names, and data types will be examined to confirm that the data has been imported correctly.

In [13]:
# Define the path to the company bankruptcy dataset
file_path = "/content/data.csv"

# Check whether the dataset file exists at the specified path
if os.path.exists(file_path):

    # Display a message confirming that the file exists
    print("File exists! Loading with pandas...")

    # Load the CSV file into a Pandas DataFrame
    df = pd.read_csv(file_path)

    # Display a message confirming that the dataset was loaded
    print("\nDataset loaded successfully!")

    # Display the first five rows of the dataset
    display(df.head())

    # Display the number of rows and columns in the dataset
    print("\nDataset shape:", df.shape)

else:

    # Display a message if the dataset file does not exist
    print("FILE DOESN'T EXIST")

File exists! Loading with pandas...

Dataset loaded successfully!

,Bankrupt,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1.0,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1.0,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1.0,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1.0,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1.0,0.035490

Dataset shape: (7780, 96)

## 3. Exploratory Data Analysis (EDA)

Exploratory Data Analysis (EDA) is an important step in understanding the characteristics and quality of the company bankruptcy dataset before applying machine learning algorithms.

This stage will involve examining the dataset structure, identifying missing values and duplicate records, analysing descriptive statistics, investigating the distribution of the target variable (`Bankrupt`), and visualizing relationships among financial indicators.

The results of EDA will help identify potential data quality issues and guide the data preprocessing and preparation stage.

### 3.1 Preview of the Dataset

The first five records of the dataset are displayed to obtain an initial understanding of the available
variables and their values.

In [14]:
# Display the first five rows of the dataset
df.head()

,Bankrupt,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1.0,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1.0,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1.0,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1.0,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1.0,0.035490

### 3.2 Preview of the Last Records

The last five records of the dataset are displayed to verify the end of the dataset and confirm that the data has been loaded correctly.

In [15]:
# Display the last five rows of the dataset
df.tail()

,Bankrupt,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
7775,0,0.493687,0.539468,0.543230,0.604455,0.604462,0.998992,0.797409,0.809331,0.303510,...,0.799927,0.000466,0.623620,0.604455,0.840359,0.279606,0.027064,0.566193,1.0,0.029890
7776,0,0.475162,0.538269,0.524172,0.598308,0.598308,0.998992,0.797414,0.809327,0.303520,...,0.799748,0.001959,0.623931,0.598306,0.840306,0.278132,0.027009,0.566018,1.0,0.038284
7777,0,0.472725,0.533744,0.520638,0.610444,0.610213,0.998984,0.797401,0.809317,0.303512,...,0.797778,0.002840,0.624156,0.610441,0.840138,0.275789,0.026791,0.565158,1.0,0.097649
7778,0,0.506264,0.559911,0.554045,0.607850,0.607850,0.999074,0.797500,0.809399,0.303498,...,0.811808,0.002837,0.623957,0.607846,0.841084,0.277547,0.026822,0.565302,1.0,0.044009
7779,0,0.493053,0.570105,0.549548,0.627409,0.627409,0.998080,0.801987,0.813800,0.313415,...,0.815956,0.000707,0.626680,0.627408,0.841019,0.275114,0.026793,0.565167,1.0,0.233902